-- DROP TABLE IF EXISTS products;
-- CREATE TABLE products (
--     id INTEGER PRIMARY KEY AUTOINCREMENT,
--     name TEXT NOT NULL,
--     description TEXT NOT NULL,
--     type TEXT NOT NULL,
--     price INTEGER NOT NULL,
--     outofstock BOOLEAN NOT NULL,
--     image TEXT NOT NULL,
--     shortname TEXT NOT NULL
-- );
-- DROP TABLE IF EXISTS cart;
-- CREATE TABLE cart (
--     id INTEGER PRIMARY KEY AUTOINCREMENT,
--     product TEXT NOT NULL,
--     quanity INTEGER NOT NULL,
--     modifiers TEXT NOT NULL,
--     price INTEGER NOT NULL,
--     user INTEGER REFERENCES users(id)
-- );
-- DROP TABLE IF EXISTS users;
-- CREATE TABLE users (
--     id INTEGER PRIMARY KEY AUTOINCREMENT,
--     username TEXT NOT NULL,
--     hash TEXT NOT NULL
-- )
DELETE FROM products WHERE name = 'Everything Bagel';
INSERT INTO products (name, description,type,price,outofstock,image,shortname) VALUES ('Everything Bagel', 'A plain old everything bagel.  Who does not love it? The rich seeds and salt combined with homemade New York bagels make for the perfect breakfast','bagel',150,0,'https://live-aroma-joes-2020.imgix.net/wp-content/uploads/2021/01/Everything-Bagel-Sandwich.png?q=85&fit=crop&crop=faces&auto=format&w=259', 'everything_bagel')